services:
  postgres:
    image: postgres:18-alpine
    container_name: crud-postgres
    environment:
      POSTGRES_DB: cruddb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.2
    container_name: crud-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    command: start-dev

  crud-api:
    image: ghcr.io/73n37/crud-application:latest
    container_name: crud-api
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cruddb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:2
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - crud-api

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-cd
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --label-enable

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
