# Application configuration
server.port=8080

# Logging level
logging.level.com.example.crudapp=DEBUG

# Database Configuration (PostgreSQL from docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5433/cruddb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Keycloak Configuration
keycloak.jwk-set-uri=http://localhost:8081/realms/crud-realm/protocol/openid-connect/certs
keycloak.issuer=http://localhost:8081/realms/crud-realm

