<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>com.org73n37</groupId>
		<artifactId>crudapp-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	
	<artifactId>crud-engine-spring-boot-starter</artifactId>
	<name>crud-engine-spring-boot-starter</name>
	<description>Spring Boot Auto-configuration Starter for CRUD Engine</description>

	<dependencies>
		<!-- Core Engine Modules -->
		<dependency>
			<groupId>com.org73n37</groupId>
			<artifactId>crud-engine-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.org73n37</groupId>
			<artifactId>crud-engine-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>com.org73n37</groupId>
			<artifactId>crud-engine-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.org73n37</groupId>
			<artifactId>crud-engine-security-keycloak</artifactId>
		</dependency>
	</dependencies>
</project>
